
task :hello do
    puts "Hello World."
end

task :make do
    puts "This is prototype for rake."
end

namespace :demo do |ns|
    task :hello do |t|
        puts "Hello 1 in demo."
        puts "Hello 2 in demo."
    end
end

